version: '2'
services:
  zookeeper:
    image: appcelerator/zookeeper:latest
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: appcelerator/kafka:latest
    ports:
      - "9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9080:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - zookeeper
  worker:
    build: ./docker/Dockerfile
    image: 
    container_name: phpkafka-worker
    volumes:
      - .:/opt/phpkafka-worker/
    depends_on:
      - kafka
